# Generated by Django 2.0.5 on 2018-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(default='./static/default.png', upload_to='profile_pictures/%Y/%m'),
        ),
    ]
