# Generated by Django 2.0.5 on 2018-10-11 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('profile_picture', models.ImageField(blank=True, default='final_app/profile_pictures/default.png', null=True, upload_to='final_app/profile_pictures')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPofileInfo',
        ),
    ]
