# Generated by Django 2.0.5 on 2018-10-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='geom',
            new_name='location',
        ),
    ]
