# Generated by Django 2.0.5 on 2018-10-10 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpofileinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, default='final_app/profile_pictures/default_profile_picture.png', null=True, upload_to='final_app/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userpofileinfo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
