# Generated by Django 2.0.5 on 2018-10-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_food_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
