# Generated by Django 2.0.5 on 2018-10-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0002_auto_20181012_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='permit',
            field=models.URLField(blank=True, null=True),
        ),
    ]
