# Generated by Django 2.0.5 on 2018-10-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20181013_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='bought',
            new_name='packed',
        ),
    ]
