# Generated by Django 2.0.5 on 2018-10-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20181013_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='post_pictures/%Y/%m'),
        ),
    ]
