# Generated by Django 2.0.5 on 2018-12-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20181207_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
