# Generated by Django 2.0.5 on 2018-10-16 22:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20181016_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
