# Generated by Django 2.0.5 on 2018-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20181015_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
