# Generated by Django 2.0.5 on 2018-10-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_auto_20181012_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/%Y/%m'),
        ),
    ]
