# Generated by Django 2.0.5 on 2018-12-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_userprofileinfo_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='privacy_choice',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=7),
        ),
    ]
