# Generated by Django 2.0.5 on 2018-10-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_auto_20181013_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
